[package]
name = "r_algorithm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "r_algorithm"
path = "src/lib.rs"

[[bin]]
name = "r_algorithm"
path = "src/bin.rs"

[dependencies]
